"""Regenerate the bundled read-only examples: python build-demo.py"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent
data = {
    "manifest": json.loads((root / "data/manifest.json").read_text(encoding="utf-8")),
    "documents": {p.relative_to(root).as_posix(): p.read_text(encoding="utf-8")
                  for p in sorted((root / "content").rglob("*.md"))},
}
(root / "js/demo-data.js").write_text(
    "// Generated by build-demo.py; edit the Markdown sources instead.\nwindow.SHOWCASE_DEMO = "
    + json.dumps(data, ensure_ascii=False) + ";\n", encoding="utf-8")
